import { useState, useEffect } from "react";
import { rpcCall, rpcSubscribe } from "./rpc";
import "./App.css";

// --- Types (matching Rust server, would be auto-generated by orpc-specta) ---

interface Planet {
  id: number;
  name: string;
  radius_km: number;
  has_rings: boolean;
}

// ---------------------------------------------------------------------------
// Ping
// ---------------------------------------------------------------------------

function PingButton() {
  const [result, setResult] = useState<string | null>(null);

  async function handlePing() {
    const res = await rpcCall<string>("ping");
    setResult(res);
  }

  return (
    <div style={{ marginBottom: 24 }}>
      <h3>Ping (IPC)</h3>
      <button onClick={handlePing}>Ping Server</button>
      {result && <pre>Response: {result}</pre>}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Planet List
// ---------------------------------------------------------------------------

function PlanetList({ refreshKey }: { refreshKey: number }) {
  const [planets, setPlanets] = useState<Planet[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    rpcCall<Planet[]>("planet.list").then((data) => {
      setPlanets(data);
      setLoading(false);
    });
  }, [refreshKey]);

  if (loading) return <p>Loading planets...</p>;

  return (
    <div style={{ marginBottom: 24 }}>
      <h3>Planet List (IPC)</h3>
      <table border={1} cellPadding={8} style={{ borderCollapse: "collapse" }}>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Radius (km)</th>
            <th>Rings</th>
          </tr>
        </thead>
        <tbody>
          {planets.map((p) => (
            <tr key={p.id}>
              <td>{p.id}</td>
              <td>{p.name}</td>
              <td>{p.radius_km.toLocaleString()}</td>
              <td>{p.has_rings ? "Yes" : "No"}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Find Planet
// ---------------------------------------------------------------------------

function FindPlanet() {
  const [name, setName] = useState("");
  const [result, setResult] = useState<Planet | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleSearch(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setResult(null);
    try {
      const planet = await rpcCall<Planet>("planet.find", { name });
      setResult(planet);
    } catch (err: any) {
      setError(err?.message ?? "Unknown error");
    }
  }

  return (
    <div style={{ marginBottom: 24 }}>
      <h3>Find Planet (IPC)</h3>
      <form onSubmit={handleSearch}>
        <input
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Planet name (e.g. Earth)"
        />
        <button type="submit" style={{ marginLeft: 8 }}>Search</button>
      </form>
      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}
      {error && <p style={{ color: "red" }}>{error}</p>}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Create Planet
// ---------------------------------------------------------------------------

function CreatePlanet({ onCreated }: { onCreated: () => void }) {
  const [result, setResult] = useState<Planet | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setResult(null);
    setLoading(true);
    try {
      const form = e.target as HTMLFormElement;
      const data = new FormData(form);
      const planet = await rpcCall<Planet>("planet.create", {
        name: data.get("name") as string,
        radius_km: Number(data.get("radius_km")),
        has_rings: data.get("has_rings") === "on",
      });
      setResult(planet);
      onCreated();
    } catch (err: any) {
      setError(err?.message ?? "Unknown error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{ marginBottom: 24 }}>
      <h3>Create Planet (IPC Mutation)</h3>
      <form onSubmit={handleCreate}>
        <div>
          <input name="name" placeholder="Name" required />
        </div>
        <div style={{ marginTop: 4 }}>
          <input name="radius_km" type="number" placeholder="Radius (km)" required />
        </div>
        <div style={{ marginTop: 4 }}>
          <label>
            <input name="has_rings" type="checkbox" /> Has rings
          </label>
        </div>
        <button type="submit" style={{ marginTop: 8 }} disabled={loading}>
          {loading ? "Creating..." : "Create"}
        </button>
      </form>
      {result && <pre>Created: {JSON.stringify(result, null, 2)}</pre>}
      {error && <p style={{ color: "red" }}>{error}</p>}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Subscription (poll-based for Tauri IPC — invoke is request-response)
// ---------------------------------------------------------------------------

function PlanetSubscription() {
  const [events, setEvents] = useState<string[]>([]);
  const [status, setStatus] = useState<"idle" | "listening" | "done" | "error">("idle");

  function handleSubscribe() {
    setEvents([]);
    setStatus("listening");

    rpcSubscribe<Planet>("planet.stream", {
      onMessage: (planet, id) => {
        setEvents((prev) => [...prev, `[${id}] ${JSON.stringify(planet)}`]);
      },
      onDone: () => setStatus("done"),
      onError: (err) => {
        setEvents((prev) => [...prev, `Error: ${JSON.stringify(err)}`]);
        setStatus("error");
      },
    });
  }

  return (
    <div style={{ marginBottom: 24 }}>
      <h3>Subscription (IPC Channel)</h3>
      <p style={{ color: "#666", fontSize: 14 }}>
        Streams newly created planets in real-time via Tauri Channel.
        Click subscribe, then create a planet above — it appears here instantly.
      </p>
      <button onClick={handleSubscribe} disabled={status === "listening"}>
        {status === "listening" ? "Listening..." : "Subscribe to Planet Updates"}
      </button>
      {events.length > 0 && (
        <pre style={{ maxHeight: 200, overflow: "auto", background: "#f5f5f5", padding: 8 }}>
          {events.join("\n")}
        </pre>
      )}
      {status === "done" && <p style={{ color: "green" }}>Stream complete</p>}
    </div>
  );
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const [refreshKey, setRefreshKey] = useState(0);

  return (
    <div style={{ maxWidth: 720, margin: "0 auto", padding: 24, fontFamily: "system-ui" }}>
      <h1>orpc-rs + Tauri</h1>
      <p style={{ color: "#666" }}>
        Same Planet demo as axum-react, but running via Tauri IPC — zero HTTP.
      </p>

      <hr />
      <h2>RPC via Tauri IPC</h2>
      <PingButton />
      <PlanetList refreshKey={refreshKey} />
      <FindPlanet />
      <CreatePlanet onCreated={() => setRefreshKey((k) => k + 1)} />

      <hr />
      <h2>Subscription</h2>
      <PlanetSubscription />
    </div>
  );
}
