// Auto-generated by orpc-specta. Do not edit.
// This file has been generated by Specta. Do not edit this file manually.
export type CreatePlanetInput = {
	name: string,
	radius_km: number,
	has_rings: boolean,
};

export type FindPlanetInput = {
	name: string,
};

export type Procedures = {
  ping: { input: never; output: never }
  planet: {
    create: { input: {
	name: string,
	radius_km: number,
	has_rings: boolean,
}; output: never }
    find: { input: {
	name: string,
}; output: never }
    list: { input: never; output: never }
    stream: { input: never; output: never }
  }
}
