// Auto-generated by orpc-specta. Do not edit.
import type { Client } from "@orpc/client"

export type CreatePlanetInput = {
	name: string,
	radius_km: number,
	has_rings: boolean,
}

export type FindPlanetInput = {
	name: string,
}

export type Planet = {
	id: number,
	name: string,
	radius_km: number,
	has_rings: boolean,
}

export type Procedures = {
  ping: Client<Record<never, never>, void, string, Error>
  planet: {
    create: Client<Record<never, never>, CreatePlanetInput, Planet, Error>
    find: Client<Record<never, never>, FindPlanetInput, Planet, Error>
    list: Client<Record<never, never>, void, Planet[], Error>
    stream: Client<Record<never, never>, void, AsyncIterableIterator<Planet>, Error>
  }
}
